[package]
name = "rust-xaml"
version = "0.1.0"
authors = ["kai <thiskaiguy@gmail.com>"]
edition = "2018"

[dependencies]
bindings = { path = "bindings" }
windows = "0.10"
winit = "0.25"

[build-dependencies]
embed-resource = "1"
